### ISSUE TITLE
Other allocators besides HeapAllocator

### ISSUE THREAD

**Issue by srijs** [dwrensha/capnp-rpc-rust#15]
Hi!

I'm at a point with a project where most of the cpu time is spent allocating/freeing memory for RPC messages.

Each client session runs in it's own thread (with it's own event loop) which is why I think it would be a great case for using and re-using thread-local allocation buffers.

It seems that capnproto-rust supports using allocators besides the default HeapAllocator, and I was wondering whether that is something that is planned for capnp-rpc-rust as well?

I am willing to take a stab at the necessary changes if you are open to taking the project in that direction.

**Comment by dwrensha** [comment]
I am aware that capnp-rpc-rust is rather heavy on heap allocations. My impression is that the bulk of the allocation burden is usually due to the gj event loop in general (which e.g. allocates closures on the heap, and encourages a heap-centric programming style), rather than due to `capnp::message::HeapAllocator` in particular. If you have made measurements that contradict this impression, I would be interested to hear more about them.  Do allocations of `gj::private::PromiseNode` show up in your measurements?

Ultimately, I think the best way forward here will be to build capnp-rpc-rust on "resumable functions" / "generators", as I sketched [here](https://dwrensha.github.io/capnproto-rust/2016/05/28/async-generators.html). This should vastly improve the ergonomics of writing async code and should greatly reduce the number of required heap allocations.

Of course, this plan requires as-yet-nonexistent features in the Rust language, so it will take some time. Until then, I'm open to strategies for reducing allocations. Maybe each `capnp_rpc::twopatry::VatNetwork` should own a pool of buffers that are re-used for messages?

**Comment by srijs** [comment]
@dwrensha sorry for the long delay. I was able to verify your assumption that a majority of allocations was due to the promises. It wasn't obvious to me at first because these are numerous but individually very small allocations.

I'm sure you've already seen Alex Crichton's [Futures library](https://github.com/alexcrichton/futures-rs) by now, which is advertised as "zero cost". OOI, what are your thoughts on trying to base capnp-rpc-rust on top of that insteaf of gj and do some benchmarks to compare the two w.r.t allocations?

**Comment by dwrensha** [comment]
futures-rs looks very interesting, especially now that it has relaxed most of the `Send` bounds it originally had: https://github.com/alexcrichton/futures-rs/commit/4d4ce22f1b39be27db962e729394775827e4619e. I am open to considering using futures-rs instead of gj. Another question would then be: which I/O library should we use? futures-mio, tokio, or something else?

**Comment by srijs** [comment]
It seems tokio is fairly opinionated in the IO pattern (request-response) that it provides, and futures-mio might give us more flexibility to implement the capability-based RPC mechanism that is necessary for cap'n'proto.

**Comment by dwrensha** [comment]
Note also that futures-mio has been renamed to [tokio-core](https://github.com/tokio-rs/tokio-core).

**Comment by srijs** [comment]
Closing this now that this crate has moved to `futures`.
